# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018
  project: TYPO3 Content - MobApp (Deutsch)
  version: 2.2
  release: 2.2.1
  latex_documents:
  - - Index
    - t3content_mobapp.tex
    - TYPO3 Content - MobApp
    - Salvatore Eckel
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
